// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-scores.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_scores_default = defineTool({
  name: "list_scores",
  title: "List sacred music scores",
  description: "List Boniface Kagunda's published sacred music scores from the public catalog. Supports filtering by ensemble and optional text search over title and story.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max scores to return (default 20)."),
    ensemble: z.string().optional().describe("Filter by ensemble_type, e.g. 'SATB Choir'."),
    search: z.string().optional().describe("Case-insensitive substring match on title."),
    featured_only: z.boolean().optional().describe("Return only featured scores.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, ensemble, search, featured_only }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("scores").select("id,title,musescore_url,thumbnail_url,ensemble_type,mood,instruments,duration,pages,story,views,featured,published_date").order("published_date", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (ensemble) q = q.eq("ensemble_type", ensemble);
    if (featured_only) q = q.eq("featured", true);
    if (search) q = q.ilike("title", `%${search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error loading scores: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { scores: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-score.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_score_default = defineTool2({
  name: "get_score",
  title: "Get score details",
  description: "Fetch full metadata for a single sacred music score by its ID.",
  inputSchema: {
    id: z2.string().uuid().describe("Score UUID from list_scores.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("scores").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Score not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { score: data }
    };
  }
});

// src/lib/mcp/tools/submit-commission.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var submit_commission_default = defineTool3({
  name: "submit_commission_inquiry",
  title: "Submit a commission inquiry",
  description: "Send a new commission inquiry to Boniface Kagunda. Use this when a user wants to request a custom sacred music composition.",
  inputSchema: {
    name: z3.string().min(1).max(120).describe("Full name of the person commissioning."),
    email: z3.string().email().max(255).describe("Contact email."),
    message: z3.string().min(1).max(4e3).describe("Details: story, occasion, lyrics, feeling."),
    occasion: z3.string().max(120).optional(),
    ensemble: z3.string().max(120).optional(),
    voice_type: z3.string().max(60).optional(),
    deadline: z3.string().max(100).optional().describe("Free-text deadline, e.g. 'Easter Vigil 2026'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const id = crypto.randomUUID();
    const { error } = await supabase.from("commission_inquiries").insert({ id, ...input });
    if (error) {
      return { content: [{ type: "text", text: `Failed to submit inquiry: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Inquiry received (id: ${id}). Boniface personally replies within 48 hours.` }],
      structuredContent: { id, status: "received" }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bk-music-mcp",
  title: "BK Music",
  version: "0.1.0",
  instructions: "Tools for exploring Boniface Kagunda's sacred music catalog and submitting commission inquiries. Use `list_scores` to browse the catalog, `get_score` to fetch a single piece, and `submit_commission_inquiry` when a user wants to request a custom composition.",
  tools: [list_scores_default, get_score_default, submit_commission_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
