
UPDATE public.scores
SET story = 'HEKO means "thank you" in the simplest, most childlike Swahili — the word a mother teaches before she teaches prayer. I wrote this piece the morning after my grandmother''s burial, sitting alone at the parish piano with the sun barely up. The right hand keeps asking the same gentle question — "asante kwa nini? thanks for what?" — and the left hand answers, again and again, the way she used to: a hand on my shoulder, no words needed. Between the lines of the melody is every meal she cooked, every hymn she hummed under her breath, every Sunday she walked me to Mass holding my smaller hand. I now place HEKO at the Communion procession, because gratitude is the only honest reply to a love we did not earn. When the choir sings it, I hear her saying: "karibu mwanangu" — welcome, my child.'
WHERE title = 'HEKO';

UPDATE public.scores
SET story = 'HALELUYA was born at 2 a.m. during a Holy Saturday vigil rehearsal. The choir was exhausted, the candles were melting onto the music stands, and a young soprano whispered, "Mwalimu, naomba tuimbe kitu cha furaha kabla hatujachoka kabisa" — "Teacher, please, one joyful thing before we collapse." I sat at the piano and the four voices found each other almost on their own — soprano leaping like a child running into a courtyard, bass laughing low underneath, alto and tenor weaving the bright thread between. Hidden inside the repeated "Haleluya" is a private prayer of mine: that joy in the Church would never again belong only to the trained voice — that the grandmother in the back pew, the boda-boda rider who slipped in late, and the child swinging her legs on the bench would all find their note. Sing it loud. Sing it tired. Sing it anyway.'
WHERE title = 'HALELUYA';

UPDATE public.scores
SET story = 'SIFA NA UTUKUFU — "Praise and Glory" — started as a finger-warm-up I played absent-mindedly before Sunday Mass. I did not think it was a piece; I thought it was a habit. Then the children in the front pew began humming it back at me on the way out of church, and a little girl named Wanjiru tugged my sleeve and said, "ile wimbo wako ya kucheka" — "your laughing song." That stayed with me. So I shaped it into a piano duo: two players, four hands, one shared smile. The primo dances above like sunlight on a tin roof after rain; the secondo claps along like the aunties at a wedding. Between the chords is a quiet conviction I want every congregation to feel — that praising God is not a duty we owe but a delight we get to keep. Short enough for a Gloria interlude, joyful enough to make even the shyest worshipper sit a little straighter.'
WHERE title = 'SIFA NA UTUKUFU';

UPDATE public.scores
SET story = 'A young couple in our parish lost an entire harvest to the floods of the long rains. I expected them to stay home that Sunday. Instead they walked up the offertory aisle carrying their last tin of maize, hands trembling, eyes steady. I could not stop watching them. I could not sing. By Monday, SADAKA TAKATIFU — "Holy Offering" — was on the page. The strings move slowly on purpose, the way a barefoot procession moves: one deliberate step, then another, then a pause to breathe. The cello carries the weight of what is being given up; the violin lifts what is being given over. Hidden between the phrases is a truth I learned that morning: the holiest offering is rarely the largest one — it is the one that costs the giver something real. Whenever a parish plays this piece at the offertory, I pray the assembly remembers that small tin of maize, and the courage it took to carry it.'
WHERE title = 'SADAKA TAKATIFU';
